import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import Footer from "./components/Footer/footer";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "DIOP",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className=" h-fit  w-full text-black antialiased pt-10">
        <SessionProvider>
          <TRPCReactProvider>{children}</TRPCReactProvider>
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
